version: "2"

services:
  haproxy:
    build: haproxy/
    ports:
      - 8080:80
    restart: always
  transmission:
    extends:
      file: media/docker-compose.yml
      service: transmission
  jackett:
    extends:
      file: media/docker-compose.yml
      service: jackett
  radarr:
    extends:
      file: media/docker-compose.yml
      service: radarr
  sonarr:
    extends:
      file: media/docker-compose.yml
      service: sonarr
  bazarr:
    extends:
      file: media/docker-compose.yml
      service: bazarr
  octorprint:
    extends:
      file: printer/docker-compose.yml
      service: octoprint
