version: "2"

services:
  haproxy:
    container_name: haproxy
    build: haproxy/
    ports:
      - 80:80
    restart: always
    depends_on:
      - transmission
      - jackett
      - radarr
      - sonarr
      - bazarr
      - octoprint
  transmission:
    extends:
      file: media/docker-compose.yml
      service: transmission
  jackett:
    extends:
      file: media/docker-compose.yml
      service: jackett
  radarr:
    extends:
      file: media/docker-compose.yml
      service: radarr
    depends_on:
      - transmission
      - jackett
  sonarr:
    extends:
      file: media/docker-compose.yml
      service: sonarr
    depends_on:
      - transmission
      - jackett
  bazarr:
    extends:
      file: media/docker-compose.yml
      service: bazarr
    depends_on:
      - transmission
      - jackett
      - radarr
      - sonarr
  octoprint:
    extends:
      file: printer/docker-compose.yml
      service: octoprint
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
