version: "2.1"

services:
  haproxy:
    build: ./haproxy
    container_name: haproxy
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /srv/dev-disk-by-label-data/AppData/transmission:/config
      - /srv/dev-disk-by-label-backup/Download:/downloads
      - /srv/dev-disk-by-label-backup/Download/torrents:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /srv/dev-disk-by-label-data/AppData/sonarr:/config
      - /srv/dev-disk-by-label-backup/Media/series:/tv
      - /srv/dev-disk-by-label-backup/Download/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

networks:
  default:
