version: "2"

services:
  config-editor:
    image: linuxserver/code-server
    container_name: config-editor
    ports:
      - 8443:8443
    depends_on:
      - haproxy
    restart: unless-stopped
    environment:
      - PUID=0
      - GUID=0
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - haproxy:/haproxy
      - /srv/dev-disk-by-label-data/AppData/code-server:/config
  haproxy:
    build: haproxy/
    container_name: haproxy
    ports:
      - 8080:80
    volumes:
      - haproxy:/usr/local/etc/haproxy
    restart: always
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /srv/dev-disk-by-label-data/AppData/transmission:/config
      - /srv/dev-disk-by-label-backup/Download:/downloads
      - /srv/dev-disk-by-label-backup/Download/torrents:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /srv/dev-disk-by-label-data/AppData/jackett:/config
      - /srv/dev-disk-by-label-backup/Download/complete:/downloads
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /srv/dev-disk-by-label-data/AppData/radarr:/config
      - /srv/dev-disk-by-label-backup/Media/movies:/movies
      - /srv/dev-disk-by-label-backup/Download/complete:/downloads
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /srv/dev-disk-by-label-data/AppData/sonarr:/config
      - /srv/dev-disk-by-label-backup/Media/series:/tv
      - /srv/dev-disk-by-label-backup/Download/complete:/downloads
    restart: unless-stopped
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /srv/dev-disk-by-label-data/AppData/bazarr:/config
      - /srv/dev-disk-by-label-backup/Media/movies:/movies
      - /srv/dev-disk-by-label-backup/Media/series:/tv
    restart: unless-stopped

volumes:
  haproxy:
